author: Nick Pegg
title: Nick Pegg
# description: ''
base_url: /

num_top_tags: 5
num_posts_per_page: -1

feeds:
  rss: True
  atom: True

# Backward compatibility tunables
compat:
  redirect_posty1_urls: True
